export const platforms = [
  {
    id: 4,
    name: "PC",
    slug: "pc",
    icon: "microsoft-windows",
  },
  {
    id: 187,
    name: "PlayStation 5",
    slug: "playstation5",
    icon: "sony-playstation",
  },
  {
    id: 18,
    name: "PlayStation 4",
    slug: "playstation4",
    icon: "sony-playstation",
  },
  {
    id: 1,
    name: "Xbox One",
    slug: "xbox-one",
    icon: "microsoft-xbox",
  },
  {
    id: 186,
    name: "Xbox Series S/X",
    slug: "xbox-series-x",
    icon: "microsoft-xbox",
  },
  {
    id: 7,
    name: "Nintendo Switch",
    slug: "nintendo-switch",
    icon: "nintendo-switch",
  },
  {
    id: 3,
    name: "iOS",
    slug: "ios",
    icon: "apple",
  },
  {
    id: 21,
    name: "Android",
    slug: "android",
    icon: "android",
  },
  {
    id: 8,
    name: "Nintendo 3DS",
    slug: "nintendo-3ds",
    icon: "nintendo-game-boy",
  },
  {
    id: 9,
    name: "Nintendo DS",
    slug: "nintendo-ds",
    icon: "nintendo-game-boy",
  },
  {
    id: 13,
    name: "Nintendo DSi",
    slug: "nintendo-dsi",
    icon: "nintendo-game-boy",
  },
  {
    id: 5,
    name: "macOS",
    slug: "macos",
    icon: "apple",
  },
  {
    id: 6,
    name: "Linux",
    slug: "linux",
    icon: "linux",
  },
  {
    id: 14,
    name: "Xbox 360",
    slug: "xbox360",
    icon: "microsoft-xbox",
  },
  {
    id: 80,
    name: "Xbox",
    slug: "xbox-old",
    icon: "microsoft-xbox",
  },
  {
    id: 16,
    name: "PlayStation 3",
    slug: "playstation3",
    icon: "sony-playstation",
  },
  {
    id: 15,
    name: "PlayStation 2",
    slug: "playstation2",
    icon: "sony-playstation",
  },
  {
    id: 27,
    name: "PlayStation",
    slug: "playstation1",
    icon: "sony-playstation",
  },
  {
    id: 19,
    name: "PS Vita",
    slug: "ps-vita",
    icon: "sony-playstation",
  },
  {
    id: 17,
    name: "PSP",
    slug: "psp",
    icon: "sony-playstation",
  },
  {
    id: 10,
    name: "Wii U",
    slug: "wii-u",
    icon: "nintendo-wiiu",
  },
  {
    id: 11,
    name: "Wii",
    slug: "wii",
    icon: "nintendo-wii",
  },
  {
    id: 105,
    name: "GameCube",
    slug: "gamecube",
    icon: "cube",
  },
  {
    id: 83,
    name: "Nintendo 64",
    slug: "nintendo-64",
    icon: "cpu-64-bit",
  },
  {
    id: 24,
    name: "Game Boy Advance",
    slug: "game-boy-advance",
    icon: "nintendo-game-boy",
  },
  {
    id: 43,
    name: "Game Boy Color",
    slug: "game-boy-color",
    icon: "nintendo-game-boy",
  },
  {
    id: 26,
    name: "Game Boy",
    slug: "game-boy",
    icon: "nintendo-game-boy",
  },
  {
    id: 79,
    name: "SNES",
    slug: "snes",
    icon: "nintendo-game-boy",
  },
  {
    id: 49,
    name: "NES",
    slug: "nes",
    icon: "nintendo-game-boy",
  },
  {
    id: 55,
    name: "Classic Macintosh",
    slug: "macintosh",
    icon: "apple",
  },
  {
    id: 41,
    name: "Apple II",
    slug: "apple-ii",
    icon: "apple",
  },
  {
    id: 166,
    name: "Commodore / Amiga",
    slug: "commodore-amiga",
    icon: "desktop-classic",
  },
  {
    id: 28,
    name: "Atari 7800",
    slug: "atari-7800",
    icon: "alpha-a-box",
  },
  {
    id: 31,
    name: "Atari 5200",
    slug: "atari-5200",
    icon: "alpha-a-box",
  },
  {
    id: 23,
    name: "Atari 2600",
    slug: "atari-2600",
    icon: "alpha-a-box",
  },
  {
    id: 22,
    name: "Atari Flashback",
    slug: "atari-flashback",
    icon: "alpha-a-box",
  },
  {
    id: 25,
    name: "Atari 8-bit",
    slug: "atari-8-bit",
    icon: "alpha-a-box",
  },
  {
    id: 34,
    name: "Atari ST",
    slug: "atari-st",
    icon: "alpha-a-box",
  },
  {
    id: 46,
    name: "Atari Lynx",
    slug: "atari-lynx",
    icon: "alpha-a-box",
  },
  {
    id: 50,
    name: "Atari XEGS",
    slug: "atari-xegs",
    icon: "alpha-a-box",
  },
  {
    id: 167,
    name: "Genesis",
    slug: "genesis",
    icon: "alpha-g-box",
  },
  {
    id: 107,
    name: "SEGA Saturn",
    slug: "sega-saturn",
    icon: "alpha-s-box",
  },
  {
    id: 119,
    name: "SEGA CD",
    slug: "sega-cd",
    icon: "alpha-s-box",
  },
  {
    id: 117,
    name: "SEGA 32X",
    slug: "sega-32x",
    icon: "alpha-s-box",
  },
  {
    id: 74,
    name: "SEGA Master System",
    slug: "sega-master-system",
    icon: "alpha-s-box",
  },
  {
    id: 106,
    name: "Dreamcast",
    slug: "dreamcast",
    icon: "alpha-d-box",
  },
  {
    id: 111,
    name: "3DO",
    slug: "3do",
    icon: "alpha-t-box",
  },
  {
    id: 112,
    name: "Jaguar",
    slug: "jaguar",
    icon: "alpha-a-box",
  },
  {
    id: 77,
    name: "Game Gear",
    slug: "game-gear",
    icon: "alpha-g-box",
  },
  {
    id: 12,
    name: "Neo Geo",
    slug: "neogeo",
    icon: "alpha-n-box",
  },
  {
    id: 171,
    name: "Web",
    slug: "web",
    icon: "web",
  },
] as const;